In [1]:
import numpy as np

In [2]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr = np.zeros((3,4))
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [9]:
arr = np.ones((2,5),dtype = int)
arr

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [10]:
a = np.arange(2,21,2)
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [15]:
arr = np.arange(1,11)
print(arr)
arr[0:5]
arr[3:7]
arr[::-1]
arr[::2]

[ 1  2  3  4  5  6  7  8  9 10]


array([1, 3, 5, 7, 9])

In [17]:
a = np.array([2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

a[5] = 99
a

array([ 2,  4,  6,  8, 10, 99, 14, 16, 18, 20])

In [18]:
a = np.array([1,2,3,4,5])

b = np.array([6,7,8,9,10])

z = a+b
z

array([ 7,  9, 11, 13, 15])

In [20]:
arr = np.array([12,3,4,5,])
b = arr*3
b

array([36,  9, 12, 15])

In [21]:
arr = np.square([3,4,5,6])
arr


array([ 9, 16, 25, 36])

In [22]:
arr = np.array([4,5,6,7,8])
arr2 = np.sum(arr)
arr2

np.int64(30)

In [23]:
arr = np.array([3,4,5,6,7])
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))

5.0
5.0
1.4142135623730951


In [27]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
arr.reshape(3,4)


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [31]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

print(np.vstack(a))
print(np.hstack(b))

[[1]
 [2]
 [3]
 [4]
 [5]]
[ 6  7  8  9 10]


In [33]:
arr = np.array([[1,2,3,4,5],
                [6,7,8,9,10]])
#arr.flatten()
arr.ravel()


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
arr = np.array([1,2,3,4,5,6,7,8,9,10])
arr2,arr3 = np.split(arr,2)
print(arr2,arr3)

[1 2 3 4 5] [ 6  7  8  9 10]


In [41]:
arr = np.arange(1,21)
arr2 = arr[arr%2 == 0]
arr2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [42]:
arr = np.array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

arr2 = arr[arr>10]
print(arr2)

[12 14 16 18 20]


In [48]:
a = np.array([1,2,3,4,5,6,7,8,9])

a[a%2 != 0] = -1
a

 


array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

In [49]:
a = np.array([1,2,3,4,5,6,7,8,9])
arr = a[a%2 != 0]
arr

array([1, 3, 5, 7, 9])

In [55]:
arr = np.array([45,67,56,78,23,35,6,7,99])
print(np.sum(arr>50))




4


In [59]:
arr = np.array([-1,-2,-3,1,2,4,4,5-3,4,-5])

arr2 = arr[arr>-1]
arr3 = (arr>-1)
arr2
arr3

array([False, False, False,  True,  True,  True,  True,  True,  True,
       False])

In [61]:
arr = np.array([-1,-2,-3,1,2,4,4,5-3,4,-5])

arr2 = arr[arr>-1]
arr2

array([1, 2, 4, 4, 2, 4])

In [67]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])

c = np.concatenate((a,b))
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])