In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])
print('array a:',a)

array a: [1 2 3]


In [4]:
b = np.arange(0,10,2)
print('array b : ',b)

array b :  [0 2 4 6 8]


In [5]:
c = np.linspace(0,1,5)
print('array c :', c)

array c : [0.   0.25 0.5  0.75 1.  ]


In [6]:
d = np.zeros((2,3))
print('array d:\n',d)

array d:
 [[0. 0. 0.]
 [0. 0. 0.]]


In [7]:
e = np.ones((3,2))
print('array e:\n',e)

array e:
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [8]:
f = np.eye(4)
print('identity matrix f:\n',f)

identity matrix f:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [9]:
a1 = np.array([1,2,3])
reshapes = np.reshape(a1,(1,3))
print('reshaped array :',reshapes)

reshaped array : [[1 2 3]]


In [10]:
f1 = np.array([[1,2],[3,4]])
flattened = np.ravel(f1)
print('flattened array:', flattened)

flattened array: [1 2 3 4]


In [11]:
e1 = np.array([[1,2,3],[4,5,6]])
transposed = np.transpose(e1)
print('transposed array :\n', transposed)

transposed array :
 [[1 4]
 [2 5]
 [3 6]]


In [12]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.vstack([a2,b2])
print('stacked arrays:\n',stacked)

stacked arrays:
 [[1 2]
 [3 4]]


In [13]:
a2 = np.array([1,2])
b2 = np.array([3,4])
stacked = np.hstack([a2,b2])
print('stacked arrays:\n',stacked)

stacked arrays:
 [1 2 3 4]


mathematical functions

In [14]:
#add to arays
g = np.array([1,2,3,4])
added = np.add(g,2)
print('added 2 to g:',added)

added 2 to g: [3 4 5 6]


In [15]:
squared = np.power(g,2)
print('squared g:',squared)

squared g: [ 1  4  9 16]


In [16]:
sqrt = np.sqrt(g)
print('square root of g:',sqrt)

square root of g: [1.         1.41421356 1.73205081 2.        ]


In [17]:
print(a1)
print(g)

[1 2 3]
[1 2 3 4]


In [18]:
a2 = np.array([1,2,3])
dot_product = np.dot(a2,g)
print('dot product of a and g:', dot_product)

ValueError: shapes (3,) and (4,) not aligned: 3 (dim 0) != 4 (dim 0)

In [19]:
print(a)
print(a1)

[1 2 3]
[1 2 3]


In [20]:
a3 = np.array([1, 2, 3])
dot_product = np.dot(a1, a)  # Dot product of a and g
print("Dot product of a1 and a:", dot_product)

Dot product of a1 and a: 14


statistical functiions

In [21]:
s = np.array([1,2,3,4])
mean = np.mean(s)
print('mean of s:',mean)

mean of s: 2.5


In [22]:
std_dev = np.std(s)
print('standard deviation of s:',std_dev)

standard deviation of s: 1.118033988749895


In [23]:
minimum =np.min(s)
print('min of s :',minimum)

min of s : 1


In [24]:
maximum = np.max(s)
print('maxi of s :',maximum)

maxi of s : 4


linear algebra functions


In [25]:
matrix = np.array([[1,2],[3,4]])


In [26]:
determinants = np.linalg.det(matrix)
print('determinant of matrix :',determinants)

determinant of matrix : -2.0000000000000004


In [27]:
inverse = np.linalg.inv(matrix)
print('inverse of matrix:\n',inverse)

inverse of matrix:
 [[-2.   1. ]
 [ 1.5 -0.5]]


random sampling

In [28]:
random_vals = np.random.rand(3)
print('random values:',random_vals)

random values: [0.15631527 0.73014429 0.61149405]


In [29]:
np.random.seed(0)

random_vals = np.random.rand(3)
print('random valaues:',random_vals)

random valaues: [0.5488135  0.71518937 0.60276338]


In [31]:
rand_ints = np.random.randint(0,10, size=5)
print('random integers:',rand_ints)

random integers: [3 7 9 3 5]


In [33]:
np.random.seed(0)
rand_ints = np.random.randint(0,10,size=5)
print('random integers:',rand_ints)

random integers: [5 0 3 3 7]


boolean and logical function

In [34]:
logical_test = np.array([True,False,True])
all_true = np.all(logical_test)
print('all elements True:',all_true)

all elements True: False


In [35]:
logical_test = np.array([False,False,False])
all_true = np.all(logical_test)
print('all elements ar true:',all_true)

all elements ar true: False


In [36]:
any_true = np.any(logical_test)  # Check if any are True
print("Any elements True:", any_true)

Any elements True: False


set operations

In [37]:
set_a = np.array([1,2,3,4])
set_b = np.array([3,4,5,6])

intersection = np.intersect1d(set_a,set_b)
print('interseion of a and b:',intersection)

interseion of a and b: [3 4]


In [38]:
union = np.union1d(set_a,set_b)
print('union of a and b:', union)

union of a and b: [1 2 3 4 5 6]


array attribute functions

In [39]:
a = np.array([1,2,3])
shape = a.shape 
size = a.size
dimensions = a.ndim
dtype = a.dtype

print("Shape of a:", shape)
print("Size of a:", size)
print("Number of dimensions of a:", dimensions)
print("Data type of a:", dtype)



Shape of a: (3,)
Size of a: 3
Number of dimensions of a: 1
Data type of a: int64


other function

In [40]:
a = np.array([1,2,3])
copied_array = np.copy(a)
print('copied array :',copied_array)

copied array : [1 2 3]


In [41]:
array_size_in_bytes = a.nbytes
print('size of a in bbytes:',array_size_in_bytes)

size of a in bbytes: 24


In [42]:
shared = np.shares_memory(a,copied_array)
print('do a and copied_array share memory?',shared)


do a and copied_array share memory? False
