In [1]:
print('hello')

hello


In [2]:
import numpy as np

In [3]:
np.__version__

'2.1.3'

In [4]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [5]:
type(my_list)

list

In [6]:
my_list

[0, 1, 2, 3, 4, 5]

In [7]:
arr = np.array(my_list)
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
print(type(arr))

<class 'numpy.ndarray'>


In [9]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [12]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [13]:
np.arange(20,10)

array([], dtype=int64)

In [14]:
np.arange(-20,10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [15]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [16]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [17]:
np.zeros([5,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
np.zeros((10,10),dtype = int)

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [19]:
np.ones(2)

array([1., 1.])

In [20]:
np.ones(2,dtype=int)

array([1, 1])

In [21]:
np.ones([2,2])

array([[1., 1.],
       [1., 1.]])

In [22]:
np.ones([4,5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
arr

array([0, 1, 2, 3, 4, 5])

In [24]:
rand(3,2)

NameError: name 'rand' is not defined

In [25]:
random.rand(3,2)

NameError: name 'random' is not defined

In [26]:
np.random.rand(3,2)

array([[0.21464085, 0.53709996],
       [0.01965686, 0.24329028],
       [0.96979293, 0.51027834]])

In [27]:
np.random.rand(3)

array([0.39021196, 0.5513236 , 0.38424114])

In [28]:
np.random.rand(4,6)

array([[0.37442764, 0.2620688 , 0.96703151, 0.58305221, 0.05245419,
        0.53754436],
       [0.02833928, 0.22991618, 0.86093722, 0.22832765, 0.55018146,
        0.21992376],
       [0.73702027, 0.92781289, 0.04790042, 0.75142678, 0.69408294,
        0.82987045],
       [0.92650475, 0.60448468, 0.52712748, 0.36987259, 0.98524656,
        0.53159695]])

In [29]:
np.random.randint(0,10)

2

In [30]:
np.random.randint(0,10,4)

array([6, 8, 9, 7], dtype=int32)

In [31]:
np.random.randint(0,10,5)

array([8, 9, 9, 4, 0], dtype=int32)

In [32]:
n = np.random.randint(10,40,(8,10))

In [33]:
n


array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [29, 30, 29, 25, 38, 24, 12, 19, 16, 11],
       [28, 26, 37, 20, 27, 19, 24, 20, 28, 33],
       [16, 32, 26, 36, 33, 38, 37, 28, 37, 28]], dtype=int32)

In [34]:
n[5]

array([29, 30, 29, 25, 38, 24, 12, 19, 16, 11], dtype=int32)

In [35]:
n[0:6]

array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [29, 30, 29, 25, 38, 24, 12, 19, 16, 11]], dtype=int32)

In [36]:
n

array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [29, 30, 29, 25, 38, 24, 12, 19, 16, 11],
       [28, 26, 37, 20, 27, 19, 24, 20, 28, 33],
       [16, 32, 26, 36, 33, 38, 37, 28, 37, 28]], dtype=int32)

In [38]:
n[::-1]

array([[16, 32, 26, 36, 33, 38, 37, 28, 37, 28],
       [28, 26, 37, 20, 27, 19, 24, 20, 28, 33],
       [29, 30, 29, 25, 38, 24, 12, 19, 16, 11],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [18, 38, 22, 31, 12, 27, 14, 38, 32, 29]], dtype=int32)

In [39]:
n

array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [29, 30, 29, 25, 38, 24, 12, 19, 16, 11],
       [28, 26, 37, 20, 27, 19, 24, 20, 28, 33],
       [16, 32, 26, 36, 33, 38, 37, 28, 37, 28]], dtype=int32)

In [40]:
n[::2]

array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [28, 26, 37, 20, 27, 19, 24, 20, 28, 33]], dtype=int32)

In [41]:
n

array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [29, 30, 29, 25, 38, 24, 12, 19, 16, 11],
       [28, 26, 37, 20, 27, 19, 24, 20, 28, 33],
       [16, 32, 26, 36, 33, 38, 37, 28, 37, 28]], dtype=int32)

In [42]:
n[0]

array([18, 38, 22, 31, 12, 27, 14, 38, 32, 29], dtype=int32)

In [43]:
n

array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [29, 30, 29, 25, 38, 24, 12, 19, 16, 11],
       [28, 26, 37, 20, 27, 19, 24, 20, 28, 33],
       [16, 32, 26, 36, 33, 38, 37, 28, 37, 28]], dtype=int32)

In [44]:
n[0:5]

array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28]], dtype=int32)

In [45]:
n[0,5]

np.int32(27)

In [46]:
n

array([[18, 38, 22, 31, 12, 27, 14, 38, 32, 29],
       [36, 37, 12, 36, 29, 28, 36, 20, 29, 22],
       [19, 23, 31, 24, 29, 30, 29, 32, 19, 32],
       [39, 17, 20, 22, 17, 32, 33, 11, 13, 23],
       [10, 19, 30, 31, 11, 21, 17, 17, 32, 28],
       [29, 30, 29, 25, 38, 24, 12, 19, 16, 11],
       [28, 26, 37, 20, 27, 19, 24, 20, 28, 33],
       [16, 32, 26, 36, 33, 38, 37, 28, 37, 28]], dtype=int32)

In [47]:
n[5,-3]

np.int32(19)

In [48]:
import numpy as np
x = np.int32(10)
print(x)

10


In [50]:
np.arange(1,13).reshape(6,2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [51]:
np.arange(1,13).reshape(5,5)

ValueError: cannot reshape array of size 12 into shape (5,5)

In [52]:
arr1 = np.array([1,2,3,4,5,6])
result = np.square(arr1)
print(result)

[ 1  4  9 16 25 36]


In [55]:
arr2  = np.array([1,  4,  9, 16, 25, 36])
result = np.sqrt(arr2, dtype=int)
print(result)


TypeError: No loop matching the specified signature and casting was found for ufunc sqrt

In [57]:
result = np.exp(arr1)
print(result)

[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349]


In [61]:
arr3 = np.array([1,2,3])
arr4 = np.array([4,5,6])

dot_product=np.dot(arr3.arr4)
print(dot_product)

AttributeError: 'numpy.ndarray' object has no attribute 'arr4'

In [63]:
arr1 = np.array([1,2,3,4])
arr2 = np.array([5,6,7,8])

reshaped_arr = arr1.reshape(2,2)
print(reshaped_arr)

[[1 2]
 [3 4]]


In [67]:
#transpose:
arr1 = np.array([[1,2,3],[4,5,6]])
trans_arr = arr1.T
print(trans_arr)

[[1 4]
 [2 5]
 [3 6]]


In [69]:
flat = arr1.flatten()
print(flat)

[1 2 3 4 5 6]


In [70]:
arr0 = ([10,20,30,40,50,60])



In [71]:
arr0 = ([10,20,30,40,50,60])

In [72]:
#mean, median, standard deviation

mean_val = np.mean(arr0)
median_val = np.median(arr0)
std_dev = np.std(arr0)


In [73]:
print(mean_val)
print(std_dev)
print(median_val)

35.0
17.07825127659933
35.0


In [ ]:
#sum,min,max

total_sum = np.sum(arr0) min_val = np.min(arr0)

In [75]:
max_val = np.max(arr0)
print(max_val)

60


In [77]:
total_sum = np.sum(arr1)
total_sum

np.int64(21)