FULL PYTHON LIBRARIES REVISE

In [30]:
import numpy as np

In [31]:
import numpy as np

# Dataset: [Student_ID, Math, Science, English, History]
data = np.array([
    [1, 78, 85, 92, 88],
    [2, 56, 72, 65, 70],
    [3, 89, 94, 90, 96],
    [4, 45, 60, 52, 58],
    [5, 99, 100, 95, 98],
    [6, 67, 76, 72, 74],
    [7, 80, 85, 88, 82],
    [8, 54, 61, 57, 63],
    [9, 91, 92, 94, 90],
    [10, 73, 78, 75, 77]
])


In [32]:
data

array([[  1,  78,  85,  92,  88],
       [  2,  56,  72,  65,  70],
       [  3,  89,  94,  90,  96],
       [  4,  45,  60,  52,  58],
       [  5,  99, 100,  95,  98],
       [  6,  67,  76,  72,  74],
       [  7,  80,  85,  88,  82],
       [  8,  54,  61,  57,  63],
       [  9,  91,  92,  94,  90],
       [ 10,  73,  78,  75,  77]])

In [33]:
data[:3]

array([[ 1, 78, 85, 92, 88],
       [ 2, 56, 72, 65, 70],
       [ 3, 89, 94, 90, 96]])

In [34]:
data[:,3]

array([92, 65, 90, 52, 95, 72, 88, 57, 94, 75])

In [35]:
data[:,3:3]

array([], shape=(10, 0), dtype=int64)

In [36]:
data.shape

(10, 5)

In [37]:
# Get Math (col=1) and English (col=3)
data[:, [1, 3]]


array([[78, 92],
       [56, 65],
       [89, 90],
       [45, 52],
       [99, 95],
       [67, 72],
       [80, 88],
       [54, 57],
       [91, 94],
       [73, 75]])

In [38]:
data[:,[2,4]]

array([[ 85,  88],
       [ 72,  70],
       [ 94,  96],
       [ 60,  58],
       [100,  98],
       [ 76,  74],
       [ 85,  82],
       [ 61,  63],
       [ 92,  90],
       [ 78,  77]])

In [39]:
data.mean()

np.float64(63.32)

In [40]:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [41]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [42]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [43]:
np.arange(2,5)

array([2, 3, 4])

In [44]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [45]:
np.arange(2,10,-2)

array([], dtype=int64)

In [47]:
data[::-1]

array([[ 10,  73,  78,  75,  77],
       [  9,  91,  92,  94,  90],
       [  8,  54,  61,  57,  63],
       [  7,  80,  85,  88,  82],
       [  6,  67,  76,  72,  74],
       [  5,  99, 100,  95,  98],
       [  4,  45,  60,  52,  58],
       [  3,  89,  94,  90,  96],
       [  2,  56,  72,  65,  70],
       [  1,  78,  85,  92,  88]])

In [49]:
data[::,-1]

array([88, 70, 96, 58, 98, 74, 82, 63, 90, 77])

In [50]:
data[:, ::-1]

array([[ 88,  92,  85,  78,   1],
       [ 70,  65,  72,  56,   2],
       [ 96,  90,  94,  89,   3],
       [ 58,  52,  60,  45,   4],
       [ 98,  95, 100,  99,   5],
       [ 74,  72,  76,  67,   6],
       [ 82,  88,  85,  80,   7],
       [ 63,  57,  61,  54,   8],
       [ 90,  94,  92,  91,   9],
       [ 77,  75,  78,  73,  10]])

In [51]:
data

array([[  1,  78,  85,  92,  88],
       [  2,  56,  72,  65,  70],
       [  3,  89,  94,  90,  96],
       [  4,  45,  60,  52,  58],
       [  5,  99, 100,  95,  98],
       [  6,  67,  76,  72,  74],
       [  7,  80,  85,  88,  82],
       [  8,  54,  61,  57,  63],
       [  9,  91,  92,  94,  90],
       [ 10,  73,  78,  75,  77]])

In [53]:
data[1:,2]

array([ 72,  94,  60, 100,  76,  85,  61,  92,  78])

In [55]:
data[1,2]

np.int64(72)

In [57]:
data[[0,1,2],[0,2,1]]

array([ 1, 72, 89])

In [58]:
data[0:2, 1]

array([78, 56])

In [59]:
data[0:2, 1]

array([78, 56])

In [60]:
data[1,0:3]

array([ 2, 56, 72])

In [61]:
data[-1,-1]

np.int64(77)

In [62]:
data[-2,-3]

np.int64(92)

In [64]:
np.linspace(0,1,3)

array([0. , 0.5, 1. ])

In [65]:
np.random.rand(5,15)

array([[0.23240208, 0.94180911, 0.52618398, 0.00340176, 0.23933654,
        0.69788201, 0.98436639, 0.13798736, 0.03175654, 0.06449246,
        0.70410249, 0.87630308, 0.53067968, 0.08787625, 0.49901978],
       [0.96822893, 0.47100836, 0.19460293, 0.3645027 , 0.45368361,
        0.81796564, 0.25565834, 0.47970829, 0.51749456, 0.44212664,
        0.01811642, 0.14133525, 0.90676574, 0.69386772, 0.5622434 ],
       [0.92696861, 0.7501788 , 0.37968786, 0.64271188, 0.19377456,
        0.79687948, 0.12884676, 0.36742886, 0.76335087, 0.66763814,
        0.46215853, 0.56006586, 0.49138542, 0.71973539, 0.61531084],
       [0.54719446, 0.01026757, 0.61257381, 0.45809495, 0.16152123,
        0.29706204, 0.48490511, 0.4533273 , 0.94840743, 0.02188012,
        0.64237054, 0.02674922, 0.66042897, 0.67909624, 0.2294928 ],
       [0.47086891, 0.037947  , 0.25752565, 0.86598602, 0.29999428,
        0.95242721, 0.89741013, 0.77724967, 0.02701704, 0.98922604,
        0.35639617, 0.02092893, 0.41951932, 

In [67]:
np.random.rand(5,15,3)

array([[[0.16447317, 0.8342078 , 0.63259211],
        [0.81683449, 0.32177453, 0.98435457],
        [0.89459997, 0.16006747, 0.88868772],
        [0.76770097, 0.77310356, 0.60918751],
        [0.58585363, 0.76064642, 0.29020522],
        [0.40170449, 0.13470418, 0.94847284],
        [0.29389731, 0.4947498 , 0.4211526 ],
        [0.79061202, 0.20929074, 0.27846386],
        [0.37904365, 0.50207801, 0.39610646],
        [0.83321909, 0.15863706, 0.73673811],
        [0.65753666, 0.89233812, 0.49965198],
        [0.57525586, 0.06169136, 0.35398546],
        [0.4570784 , 0.05192266, 0.90493529],
        [0.43298668, 0.63738159, 0.42025255],
        [0.99361517, 0.21467766, 0.14566019]],

       [[0.00144471, 0.26763143, 0.09804041],
        [0.7448914 , 0.31850154, 0.91695855],
        [0.80761621, 0.45962586, 0.56386315],
        [0.40377411, 0.15041298, 0.49893402],
        [0.80662305, 0.98426524, 0.32078248],
        [0.99149396, 0.00734689, 0.44487514],
        [0.61827237, 0.54110879,

In [68]:
np.random.rand(1,2)

array([[0.30074682, 0.6063296 ]])

In [69]:
np.random.rand(1,2,3)

array([[[0.48933606, 0.54395218, 0.60357956],
        [0.08796777, 0.37409359, 0.3793882 ]]])

In [70]:
np.random.rand(6)

array([0.48465173, 0.40502036, 0.62831254, 0.86164587, 0.20307345,
       0.97655797])

In [71]:
np.random.randn(6)

array([-0.88659922, -1.50289161,  0.79011741,  0.91597751,  0.71639778,
       -0.52017812])

In [72]:
np.random.randn(3,5)

array([[ 0.85333633, -0.38783115, -0.64034259, -0.4334339 , -0.23073551],
       [-0.32452231,  1.58906919, -1.79181459,  0.9306051 ,  0.7616723 ],
       [-0.21340739, -0.91468329, -0.45155439, -1.11687111,  0.77875561]])

In [73]:
np.random.randn(3,5,4)

array([[[-1.79087446,  1.1766642 , -2.04034536, -1.09765996],
        [ 0.58196349,  0.50227239, -0.60618873, -1.10350465],
        [-0.24618635,  0.82418616,  0.3804621 , -0.98125003],
        [ 1.30359129,  0.32921074,  0.03953203, -0.30615649],
        [ 0.20291909, -0.35486512, -1.06716783,  0.47292095]],

       [[ 0.58138508, -0.80757392, -0.75136938,  0.37474164],
        [ 0.19356193,  0.43650629,  0.07616324, -0.14262201],
        [ 0.43481327,  0.16302298,  0.81169374,  2.3485039 ],
        [ 0.99888881, -0.30842324,  0.6131515 , -1.37609138],
        [ 0.76441247, -0.35277192, -1.02496891, -0.77410695]],

       [[ 0.11820076, -0.3457304 ,  0.76136037,  0.5775312 ],
        [-0.01832095,  0.79488868,  1.08296938,  0.22713891],
        [-0.28545837,  1.14158008,  0.24248277,  0.84027776],
        [ 1.20527236, -1.01568069, -0.13108074, -0.49372331],
        [ 0.71046419,  1.02068402,  0.35611911,  0.74212882]]])

In [74]:
np.random.randint(4,7,3)

array([5, 5, 4], dtype=int32)

In [76]:
data.shape

(10, 5)

In [78]:
data.size

50

In [79]:
data.ndim

2

In [80]:
data.dtype

dtype('int64')

In [81]:
data.itemsize

8

In [83]:
data.T

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 78,  56,  89,  45,  99,  67,  80,  54,  91,  73],
       [ 85,  72,  94,  60, 100,  76,  85,  61,  92,  78],
       [ 92,  65,  90,  52,  95,  72,  88,  57,  94,  75],
       [ 88,  70,  96,  58,  98,  74,  82,  63,  90,  77]])

In [85]:
data[5,3]

np.int64(72)

In [86]:
data[:,2]

array([ 85,  72,  94,  60, 100,  76,  85,  61,  92,  78])

In [87]:
data.T

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 78,  56,  89,  45,  99,  67,  80,  54,  91,  73],
       [ 85,  72,  94,  60, 100,  76,  85,  61,  92,  78],
       [ 92,  65,  90,  52,  95,  72,  88,  57,  94,  75],
       [ 88,  70,  96,  58,  98,  74,  82,  63,  90,  77]])

In [88]:
data[1:4, :]

array([[ 2, 56, 72, 65, 70],
       [ 3, 89, 94, 90, 96],
       [ 4, 45, 60, 52, 58]])

In [89]:
data[:, [0,2]]

array([[  1,  85],
       [  2,  72],
       [  3,  94],
       [  4,  60],
       [  5, 100],
       [  6,  76],
       [  7,  85],
       [  8,  61],
       [  9,  92],
       [ 10,  78]])

In [90]:
data[::2, ::2]

array([[  1,  85,  88],
       [  3,  94,  96],
       [  5, 100,  98],
       [  7,  85,  82],
       [  9,  92,  90]])

In [91]:
data[::-2,::-2]

array([[77, 78, 10],
       [63, 61,  8],
       [74, 76,  6],
       [58, 60,  4],
       [70, 72,  2]])

In [92]:
data[data>5]

array([ 78,  85,  92,  88,  56,  72,  65,  70,  89,  94,  90,  96,  45,
        60,  52,  58,  99, 100,  95,  98,   6,  67,  76,  72,  74,   7,
        80,  85,  88,  82,   8,  54,  61,  57,  63,   9,  91,  92,  94,
        90,  10,  73,  78,  75,  77])

In [95]:
np.add(4,3)

np.int64(7)

In [96]:
np.sum(data)

np.int64(3166)

In [97]:
np.mean(data)

np.float64(63.32)

In [98]:
np.median(data)

np.float64(73.5)

In [99]:
np.std(data)

np.float64(31.80970920961083)

In [100]:
np.var(data)

np.float64(1011.8575999999999)

In [101]:
np.min(data)

np.int64(1)

In [102]:
np.max(data)

np.int64(100)

In [103]:
np.argmin(data)

np.int64(0)

In [104]:
np.argmax(data)

np.int64(22)

In [105]:
np.percentile(data, 87)

np.float64(93.26)

In [106]:
np.cumsum(data)

array([   1,   79,  164,  256,  344,  346,  402,  474,  539,  609,  612,
        701,  795,  885,  981,  985, 1030, 1090, 1142, 1200, 1205, 1304,
       1404, 1499, 1597, 1603, 1670, 1746, 1818, 1892, 1899, 1979, 2064,
       2152, 2234, 2242, 2296, 2357, 2414, 2477, 2486, 2577, 2669, 2763,
       2853, 2863, 2936, 3014, 3089, 3166])

In [108]:
np.cumprod(data)

array([                   1,                   78,                 6630,
                     609960,             53676480,            107352960,
                 6011765760,         432847134720,       28135063756800,
           1969454462976000,     5908363388928000,   525844341614592000,
       -5910864109357006848,  2977808295446380544,  9168435257209257984,
        -219747118582071296,  8558123737516343296, -3021409812886847488,
        8907386393269895168,   119576745786474496,   597883728932372480,
        3850256943176220672, -2355931230278516736, -2452537991944470528,
        -541050252333940736, -3246301514003644416,  3858727446270443520,
       -1884619262799118336, -6565378405569658880, -6222656095706415104,
       -6665104522525802496,  1747216335512797184,   939435928911347712,
        8883385449360392192,  9014587972879646720, -1670272511801032704,
        2039004731291992064, -4747919907155345408,  6069726397788585984,
       -4988862487219666944, -8006274237557899264, 

np.dot(6,9)

In [115]:
a = np.array([[1,2,3,4,5,6,7,8,9],[3,4,5,6,7,7,9,6,5]])

In [118]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [3, 4, 5, 6, 7, 7, 9, 6, 5]])

In [123]:
a.reshape(3,6)

array([[1, 2, 3, 4, 5, 6],
       [7, 8, 9, 3, 4, 5],
       [6, 7, 7, 9, 6, 5]])

In [124]:
a.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 7, 9, 6, 5])

In [126]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 3, 4, 5, 6, 7, 7, 9, 6, 5])

In [128]:
a.transpose()

array([[1, 3],
       [2, 4],
       [3, 5],
       [4, 6],
       [5, 7],
       [6, 7],
       [7, 9],
       [8, 6],
       [9, 5]])

In [129]:
a.resize(2,9)

In [130]:
a

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [3, 4, 5, 6, 7, 7, 9, 6, 5]])

In [131]:
np.expand_dims(a, axis=0)

array([[[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [3, 4, 5, 6, 7, 7, 9, 6, 5]]])

In [132]:
np.hstack([5,8])

array([5, 8])

In [133]:
np.vstack([5,8])

array([[5],
       [8]])

In [137]:
np.split(data,5)

[array([[ 1, 78, 85, 92, 88],
        [ 2, 56, 72, 65, 70]]),
 array([[ 3, 89, 94, 90, 96],
        [ 4, 45, 60, 52, 58]]),
 array([[  5,  99, 100,  95,  98],
        [  6,  67,  76,  72,  74]]),
 array([[ 7, 80, 85, 88, 82],
        [ 8, 54, 61, 57, 63]]),
 array([[ 9, 91, 92, 94, 90],
        [10, 73, 78, 75, 77]])]

In [138]:
np.hsplit(data,5)

[array([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]]),
 array([[78],
        [56],
        [89],
        [45],
        [99],
        [67],
        [80],
        [54],
        [91],
        [73]]),
 array([[ 85],
        [ 72],
        [ 94],
        [ 60],
        [100],
        [ 76],
        [ 85],
        [ 61],
        [ 92],
        [ 78]]),
 array([[92],
        [65],
        [90],
        [52],
        [95],
        [72],
        [88],
        [57],
        [94],
        [75]]),
 array([[88],
        [70],
        [96],
        [58],
        [98],
        [74],
        [82],
        [63],
        [90],
        [77]])]

In [139]:
np.vsplit(data,5)

[array([[ 1, 78, 85, 92, 88],
        [ 2, 56, 72, 65, 70]]),
 array([[ 3, 89, 94, 90, 96],
        [ 4, 45, 60, 52, 58]]),
 array([[  5,  99, 100,  95,  98],
        [  6,  67,  76,  72,  74]]),
 array([[ 7, 80, 85, 88, 82],
        [ 8, 54, 61, 57, 63]]),
 array([[ 9, 91, 92, 94, 90],
        [10, 73, 78, 75, 77]])]

In [140]:
np.sort(data)

array([[  1,  78,  85,  88,  92],
       [  2,  56,  65,  70,  72],
       [  3,  89,  90,  94,  96],
       [  4,  45,  52,  58,  60],
       [  5,  95,  98,  99, 100],
       [  6,  67,  72,  74,  76],
       [  7,  80,  82,  85,  88],
       [  8,  54,  57,  61,  63],
       [  9,  90,  91,  92,  94],
       [ 10,  73,  75,  77,  78]])

In [141]:
np.argsort(data)

array([[0, 1, 2, 4, 3],
       [0, 1, 3, 4, 2],
       [0, 1, 3, 2, 4],
       [0, 1, 3, 4, 2],
       [0, 3, 4, 1, 2],
       [0, 1, 3, 4, 2],
       [0, 1, 4, 2, 3],
       [0, 1, 3, 2, 4],
       [0, 4, 1, 2, 3],
       [0, 1, 3, 4, 2]])

In [142]:
np.unique(data)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  45,  52,  54,
        56,  57,  58,  60,  61,  63,  65,  67,  70,  72,  73,  74,  75,
        76,  77,  78,  80,  82,  85,  88,  89,  90,  91,  92,  94,  95,
        96,  98,  99, 100])

In [143]:
np.where(data>10)

(array([0, 0, 0, 0, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 5, 5,
        5, 5, 6, 6, 6, 6, 7, 7, 7, 7, 8, 8, 8, 8, 9, 9, 9, 9]),
 array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2,
        3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]))

In [144]:
np.nonzero(data)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
        4, 4, 4, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 7, 7, 7, 7, 7, 8, 8, 8, 8,
        8, 9, 9, 9, 9, 9]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1,
        2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3,
        4, 0, 1, 2, 3, 4]))

In [146]:
np.in1d(data,7)

C:\Users\aashutosh\AppData\Local\Temp\ipykernel_11004\3772761484.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(data,7)


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False,  True, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [147]:
b = np.array([4,3,6,7,9,7,3,4])
b

array([4, 3, 6, 7, 9, 7, 3, 4])

In [148]:
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [150]:
np.intersect1d(a,b)

array([3, 4, 6, 7, 9])

In [151]:
np.setdiff1d(a,b)

array([1, 2, 5, 8])

In [153]:
np.setxor1d(a,b)

array([1, 2, 5, 8])